### ISSUE TITLE
jQuery dependency

### ISSUE THREAD

**Issue by bestander** [Fundoo-Solutions/angularjs-modal-service#1]
Hi, is jQuery actually necessary for this service?
I find that it is only used in this line: modalEl.css('top', $document.scrollTop() + 45);

I removed jQuery and left it this way modalEl.css('top', '45px'); and it works for me.

**Comment by abhrp** [comment]
no, jQuery is not necessary, we can remove the dependencies for it after removing the $document.scrollTop() part.

**Comment by bestander** [comment]
Cool, I've done this on my fork and am planning to expose this lib as bower component.
Do you want me to make pull requests to your repo with jquery removal, bower.json and a few e2e tests?

Also in my fork I've hardcoded modalEl.css('top', '200px'); and it works all right for even scrolled window.
What is the use case when $document.scrollTop() is helpful?

**Comment by shyamseshadri** [comment]
Awesome!

We would love to see a pull request with those changes.

The $document.scrollTop() was with one particular case where when the page was scrolled down, and had a lot of fixed and absolute positioning, then a portion of the modal would be out of the view. I think though that it is an edge case, and a fixed 200px is ok for now (possibly make that customizable at a later point).

**Comment by shyamseshadri** [comment]
THis is now fixed on master
