### ISSUE TITLE
console.log preventing IE users from showing the modal window

### ISSUE THREAD

**Issue by bibinbalakrishnan** [Fundoo-Solutions/angularjs-modal-service#3]
While testing on IE9 found that modal window is not getting showed up because of console.log statements in app.js. Due to IE bug, console object will get defined only after you open developer tool bar, once initialized it will start working in the same window session. So to make IE users happy, app.js should wrap console.log statement in "if(window.console)"

**Comment by shyamseshadri** [comment]
We'll get this done!

**Comment by shyamseshadri** [comment]
This has been handled in index.html
