### ISSUE TITLE
Would like option of passing template inline (template vs templateUrl)

### ISSUE THREAD

**Issue by bcamp1973** [Fundoo-Solutions/angularjs-modal-service#4]
It would be great to be able to pass in a template string as an option, many of my simple modal templates are nothing more than a line of text. Since the rest of the modal structure is already provided it would be nice to just pass in that line of text and not worry about creating/calling/caching another template. Are there any plans to add this?

**Comment by shyamseshadri** [comment]
We can totally do this, or if you want to send a PR, we would love to merge it in!

**Comment by bcamp1973** [comment]
I'd be happy to take a crack at it. The question is the approach to take I guess. I don't want to make breaking changes for current users. My first thought is to keep accepting a string as the first argument for the _templateUrl_. Alternatively, users could pass **just** an object literal that accepts either a _template_ or _templateUrl_ parameter. So, accept the current syntax to prevent breaking it...

``` javascript
createDialog('/path/to/my/template.html', {...}, {...})
```

and accept both...

``` javascript
createDialog({
    template:'<p>My template</p>'
    ...
},{...})
```

and...

``` javascript
createDialog({
    templateUrl:'/path/to/my/template.html'
    ...
},{...})
```

Does this sound like a sound approach? Alternatively, the current _templateUrl_ string could be parsed using regex, but I wonder if that approach would be difficult given the myriad of extensions in the wild that we'd have to match against? Anyway, if this approach makes sense to you I'd be happy to make a PR...

**Comment by bestander** [comment]
Hi I've done this in my fork, it may be helpful: https://github.com/bestander/angularjs-modal-service/commit/3dbb4e07fd490f33c9da72a9c61f2db365de22f0

Sorry for not submitting this as a PR. 
I just had to do many changes quickly for my project like getting rid of bootstrap dependency, adding bower manifest etc, just did not have time to push them as separate feature pull requests.

**Comment by uberspeck** [comment]
I took a slightly different approach, but I like that you can pass a jQuery/jqLite object. I may add that to mine as well. I'll post a link here once I'm finished.

**Comment by uberspeck** [comment]
Here's the approach i took...not sure if it's ideal, but it's pretty flexible. It allows me to simply pass text to the modal without any markup which works well for simple notifications and confirmations...

https://github.com/uberspeck/angularjs-modal-service/commit/586547f3e52371c3cde8333da8b9db09bc978fe5#src/createDialog.js

**Comment by shyamseshadri** [comment]
THanks for the PR, I have merged it.
